Add CoST IDS coverage notebook
open-contracting/notebooks-oc4ids pull request #34
Opened 2022-03-30 03:36 UTC by duncandewhurst

Related to [CRM-7185](https://crm.open-contracting.org/issues/7185)

2022-03-30 12:55 UTC, odscrachel requested changes
The title of the notebook here is 'Indicator Coverage', it should be 'CoST IDS Coverage '. The rest looks okay

2022-03-30 12:56 UTC, odscrachel approved these changes

2022-03-30 16:08 UTC, jpmckinney commented on README.md
> +[Indicator Coverage](https://github.com/open-contracting/oc4ids_database/blob/main/OC4IDS_CoST_IDS_Coverage.ipynb) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https
```suggestion
[CoST IDS Coverage](https://github.com/open-contracting/oc4ids_database/blob/main/OC4IDS_CoST_IDS_Coverage.ipynb) | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/open-contracting/oc4ids_database/blob/main/OC4IDS_CoST_IDS_Coverage.ipynb) | Use this notebook to calculate the coverage of the CoST Infrastructure Data Standard (IDS), according to the [CoST IDS to OC4IDS mapping](https://standard.open-contracting.org/infrastructure/latest/en/cost/#cost-ids-to-oc4ids-mapping).
```

2022-04-11 13:53 UTC, odscrachel approved these changes

2022-04-11 21:53 UTC, merged